// Mocks generated by Mockito 5.4.6 from annotations
// in quiz/test/quiz_agent_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/ai/ai_provider.dart' as _i2;
import 'package:core/ai/prompt_manager.dart' as _i6;
import 'package:core/models/intent_result.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAIResponse_0 extends _i1.SmartFake implements _i2.AIResponse {
  _FakeAIResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuizGenerationResult_1 extends _i1.SmartFake
    implements _i2.QuizGenerationResult {
  _FakeQuizGenerationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIntentResult_2 extends _i1.SmartFake implements _i3.IntentResult {
  _FakeIntentResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGradeResult_3 extends _i1.SmartFake implements _i2.GradeResult {
  _FakeGradeResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AIProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIProvider extends _i1.Mock implements _i2.AIProvider {
  MockAIProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AIResponse> generateAnswer({
    required String? query,
    required List<String>? contextDocs,
    List<Map<String, String>>? history = const [],
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateAnswer, [], {
              #query: query,
              #contextDocs: contextDocs,
              #history: history,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<_i2.AIResponse>.value(
              _FakeAIResponse_0(
                this,
                Invocation.method(#generateAnswer, [], {
                  #query: query,
                  #contextDocs: contextDocs,
                  #history: history,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AIResponse>);

  @override
  _i4.Future<_i2.QuizGenerationResult> generateQuiz({
    required String? content,
    required int? minCount,
    required int? maxCount,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateQuiz, [], {
              #content: content,
              #minCount: minCount,
              #maxCount: maxCount,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<_i2.QuizGenerationResult>.value(
              _FakeQuizGenerationResult_1(
                this,
                Invocation.method(#generateQuiz, [], {
                  #content: content,
                  #minCount: minCount,
                  #maxCount: maxCount,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.QuizGenerationResult>);

  @override
  _i4.Future<_i3.IntentResult> analyzeIntent({
    required String? text,
    List<String>? existingFiles = const [],
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeIntent, [], {
              #text: text,
              #existingFiles: existingFiles,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<_i3.IntentResult>.value(
              _FakeIntentResult_2(
                this,
                Invocation.method(#analyzeIntent, [], {
                  #text: text,
                  #existingFiles: existingFiles,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.IntentResult>);

  @override
  _i4.Future<String> summarize({
    required String? content,
    int? maxLength = 200,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#summarize, [], {
              #content: content,
              #maxLength: maxLength,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#summarize, [], {
                  #content: content,
                  #maxLength: maxLength,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.GradeResult> gradeAnswer({
    required String? question,
    required String? referenceAnswer,
    required String? userAnswer,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gradeAnswer, [], {
              #question: question,
              #referenceAnswer: referenceAnswer,
              #userAnswer: userAnswer,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<_i2.GradeResult>.value(
              _FakeGradeResult_3(
                this,
                Invocation.method(#gradeAnswer, [], {
                  #question: question,
                  #referenceAnswer: referenceAnswer,
                  #userAnswer: userAnswer,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GradeResult>);

  @override
  _i4.Future<List<double>> generateEmbedding({required String? text}) =>
      (super.noSuchMethod(
            Invocation.method(#generateEmbedding, [], {#text: text}),
            returnValue: _i4.Future<List<double>>.value(<double>[]),
          )
          as _i4.Future<List<double>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PromptManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromptManager extends _i1.Mock implements _i6.PromptManager {
  MockPromptManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get knownAgents =>
      (super.noSuchMethod(
            Invocation.getter(#knownAgents),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<String> loadTemplate(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#loadTemplate, [agentName]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#loadTemplate, [agentName]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  String render(String? template, Map<String, String>? variables) =>
      (super.noSuchMethod(
            Invocation.method(#render, [template, variables]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#render, [template, variables]),
            ),
          )
          as String);

  @override
  _i4.Future<void> saveCustomTemplate(String? agentName, String? template) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomTemplate, [agentName, template]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetOverride(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#resetOverride, [agentName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetAllOverrides() =>
      (super.noSuchMethod(
            Invocation.method(#resetAllOverrides, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.PromptTemplateInfo>> getAllTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTemplates, []),
            returnValue: _i4.Future<List<_i6.PromptTemplateInfo>>.value(
              <_i6.PromptTemplateInfo>[],
            ),
          )
          as _i4.Future<List<_i6.PromptTemplateInfo>>);

  @override
  _i4.Future<String> getOriginalTemplate(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#getOriginalTemplate, [agentName]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getOriginalTemplate, [agentName]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String?> getCustomTemplate(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomTemplate, [agentName]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> hasOverride(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#hasOverride, [agentName]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> exportAll() =>
      (super.noSuchMethod(
            Invocation.method(#exportAll, []),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.method(#exportAll, [])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<int> importFromJson(String? jsonString) =>
      (super.noSuchMethod(
            Invocation.method(#importFromJson, [jsonString]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  String displayNameOf(String? agentName) =>
      (super.noSuchMethod(
            Invocation.method(#displayNameOf, [agentName]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#displayNameOf, [agentName]),
            ),
          )
          as String);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
