name: quiz
description: 知维 Quiz 包 - 题库、测验、阅卷
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_riverpod: ^3.3.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
